# Generated by Django 3.2.5 on 2021-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(help_text='Select people who performed in this film', related_name='actors', to='catalog.Person'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(help_text='Select person or people who directed this film', related_name='director', to='catalog.Person'),
        ),
    ]
