# Generated by Django 3.2.5 on 2021-07-14 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210714_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1890), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter primary language of flim (e.g. French)', max_length=100),
        ),
    ]
