# Generated by Django 3.2.5 on 2021-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210714_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['rating', 'film', 'date_watched']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='dates_watched',
        ),
        migrations.AddField(
            model_name='review',
            name='date_watched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='IMDb id'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter primary language of film (e.g. French)', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Great'), (5, 'Amazing')]),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
