# Generated by Django 3.2.5 on 2021-07-15 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210714_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this review in entire database', primary_key=True, serialize=False),
        ),
    ]
