# Generated by Django 3.2.5 on 2021-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210720_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Director'), (2, 'Actor')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Great'), (5, 'Amazing')], default=0),
        ),
    ]
