# Generated by Django 3.2.5 on 2021-07-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210720_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title', 'year']},
        ),
    ]
