# Generated by Django 3.2.6 on 2021-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_film_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this film', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='IMDb id'),
        ),
        migrations.AlterField(
            model_name='film',
            name='plot',
            field=models.TextField(blank=True, help_text='Enter a brief description of the film', max_length=1000),
        ),
    ]
