# Generated by Django 3.2.6 on 2021-08-06 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210805_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_watched']},
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='language',
        ),
        migrations.RemoveField(
            model_name='film',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.RemoveField(
            model_name='review',
            name='private',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_watched',
            field=models.DateField(default=datetime.date(2021, 8, 6)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="review",
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
